# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiqt5.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 594)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(600, 600))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 120, 171, 111))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 151, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.heightInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.heightInput.setObjectName("heightInput")
        self.gridLayout.addWidget(self.heightInput, 0, 1, 1, 1)
        self.lengthInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lengthInput.setObjectName("lengthInput")
        self.gridLayout.addWidget(self.lengthInput, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 120, 211, 111))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 177, 74))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.filtersizeInput = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.filtersizeInput.setPlaceholderText("")
        self.filtersizeInput.setObjectName("filtersizeInput")
        self.gridLayout_2.addWidget(self.filtersizeInput, 1, 1, 1, 1)
        self.pixelfilterInput = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.pixelfilterInput.setPlaceholderText("")
        self.pixelfilterInput.setObjectName("pixelfilterInput")
        self.gridLayout_2.addWidget(self.pixelfilterInput, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.fpsInput = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.fpsInput.setObjectName("fpsInput")
        self.gridLayout_2.addWidget(self.fpsInput, 2, 1, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 70, 311, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.videoPath = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.videoPath.setObjectName("videoPath")
        self.horizontalLayout_2.addWidget(self.videoPath)
        self.browseVideo = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.browseVideo.setObjectName("browseVideo")
        self.horizontalLayout_2.addWidget(self.browseVideo)
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 311, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.picturePath = QtWidgets.QLineEdit(self.layoutWidget)
        self.picturePath.setText("")
        self.picturePath.setObjectName("picturePath")
        self.horizontalLayout.addWidget(self.picturePath)
        self.browsePicture = QtWidgets.QPushButton(self.layoutWidget)
        self.browsePicture.setObjectName("browsePicture")
        self.horizontalLayout.addWidget(self.browsePicture)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 240, 561, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 30, 311, 31))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.dataInput = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.dataInput.setObjectName("dataInput")
        self.horizontalLayout_3.addWidget(self.dataInput)
        self.browseData = QtWidgets.QPushButton(self.layoutWidget_3)
        self.browseData.setObjectName("browseData")
        self.horizontalLayout_3.addWidget(self.browseData)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(340, 20, 201, 171))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(11, 31, 181, 46))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.flameDirection = QtWidgets.QComboBox(self.layoutWidget_2)
        self.flameDirection.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.flameDirection.setObjectName("flameDirection")
        self.flameDirection.addItem("")
        self.flameDirection.addItem("")
        self.gridLayout_3.addWidget(self.flameDirection, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.dataHandle = QtWidgets.QComboBox(self.layoutWidget_2)
        self.dataHandle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dataHandle.setObjectName("dataHandle")
        self.dataHandle.addItem("")
        self.dataHandle.addItem("")
        self.dataHandle.addItem("")
        self.gridLayout_3.addWidget(self.dataHandle, 1, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 90, 181, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.flameheightInput = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.flameheightInput.setReadOnly(False)
        self.flameheightInput.setObjectName("flameheightInput")
        self.gridLayout_5.addWidget(self.flameheightInput, 0, 1, 1, 1)
        self.flamelengthInput = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.flamelengthInput.setReadOnly(False)
        self.flamelengthInput.setObjectName("flamelengthInput")
        self.gridLayout_5.addWidget(self.flamelengthInput, 1, 1, 1, 1)
        self.processButton = QtWidgets.QPushButton(self.groupBox_3)
        self.processButton.setGeometry(QtCore.QRect(10, 220, 91, 21))
        self.processButton.setObjectName("processButton")
        self.saveexcelButton = QtWidgets.QPushButton(self.groupBox_3)
        self.saveexcelButton.setGeometry(QtCore.QRect(120, 220, 91, 21))
        self.saveexcelButton.setObjectName("saveexcelButton")
        self.plotButton = QtWidgets.QPushButton(self.groupBox_3)
        self.plotButton.setGeometry(QtCore.QRect(230, 220, 75, 23))
        self.plotButton.setObjectName("plotButton")
        self.check1 = QtWidgets.QPushButton(self.groupBox_3)
        self.check1.setGeometry(QtCore.QRect(330, 220, 75, 23))
        self.check1.setObjectName("check1")
        self.processVideo = QtWidgets.QPushButton(self.tab)
        self.processVideo.setGeometry(QtCore.QRect(460, 130, 75, 23))
        self.processVideo.setObjectName("processVideo")
        self.saveButton = QtWidgets.QPushButton(self.tab)
        self.saveButton.setGeometry(QtCore.QRect(460, 180, 75, 23))
        self.saveButton.setObjectName("saveButton")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(390, 0, 181, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 146, 96))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.batchBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.batchBox.setChecked(False)
        self.batchBox.setTristate(False)
        self.batchBox.setObjectName("batchBox")
        self.verticalLayout.addWidget(self.batchBox)
        self.cropBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.cropBox.setChecked(False)
        self.cropBox.setTristate(False)
        self.cropBox.setObjectName("cropBox")
        self.verticalLayout.addWidget(self.cropBox)
        self.previousBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.previousBox.setChecked(False)
        self.previousBox.setTristate(False)
        self.previousBox.setObjectName("previousBox")
        self.verticalLayout.addWidget(self.previousBox)
        self.cropvideoBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.cropvideoBox.setChecked(False)
        self.cropvideoBox.setTristate(False)
        self.cropvideoBox.setObjectName("cropvideoBox")
        self.verticalLayout.addWidget(self.cropvideoBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Flame Speed Tool"))
        self.groupBox.setTitle(_translate("MainWindow", "Croped Area Dimensions"))
        self.label_3.setText(_translate("MainWindow", "Length (ft)"))
        self.label_2.setText(_translate("MainWindow", "Height (ft)"))
        self.heightInput.setText(_translate("MainWindow", "8"))
        self.lengthInput.setText(_translate("MainWindow", "24"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Video Processing Inputs"))
        self.filtersizeInput.setText(_translate("MainWindow", "5"))
        self.pixelfilterInput.setText(_translate("MainWindow", "150"))
        self.label_4.setText(_translate("MainWindow", "Image Filter Size"))
        self.label_5.setText(_translate("MainWindow", "Pixel Filter (0-255)"))
        self.label_10.setText(_translate("MainWindow", "Recorded FPS"))
        self.fpsInput.setText(_translate("MainWindow", "3000"))
        self.label_6.setText(_translate("MainWindow", "Video Path"))
        self.browseVideo.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Image Path"))
        self.browsePicture.setText(_translate("MainWindow", "Browse"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Data Handle"))
        self.label_7.setText(_translate("MainWindow", "Data Input File"))
        self.browseData.setText(_translate("MainWindow", "Browse"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Flame Properties"))
        self.label_8.setText(_translate("MainWindow", "Flame Direction"))
        self.flameDirection.setItemText(0, _translate("MainWindow", "Left"))
        self.flameDirection.setItemText(1, _translate("MainWindow", "Right"))
        self.label_9.setText(_translate("MainWindow", "Data Handle"))
        self.dataHandle.setItemText(0, _translate("MainWindow", "Max"))
        self.dataHandle.setItemText(1, _translate("MainWindow", "Height"))
        self.dataHandle.setItemText(2, _translate("MainWindow", "Avg"))
        self.label_13.setText(_translate("MainWindow", "Flame Length (ft)"))
        self.label_14.setText(_translate("MainWindow", "Flame Height (ft)"))
        self.flameheightInput.setText(_translate("MainWindow", "1"))
        self.flamelengthInput.setText(_translate("MainWindow", "1"))
        self.processButton.setText(_translate("MainWindow", "Process Data"))
        self.saveexcelButton.setText(_translate("MainWindow", "Save to Excel"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.check1.setText(_translate("MainWindow", "Check"))
        self.processVideo.setText(_translate("MainWindow", "Process"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Modes"))
        self.batchBox.setText(_translate("MainWindow", "Batch Mode"))
        self.cropBox.setText(_translate("MainWindow", "Crop from Video"))
        self.previousBox.setText(_translate("MainWindow", "Use Previous Image"))
        self.cropvideoBox.setText(_translate("MainWindow", "Crop Video"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

